WebAppPedidos/Models/Pedido.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace WebAppPedidos.Models
{
    public class Pedido
    {
        public int PedidoId { get; set; }
        
        [Required]
        public string Produto { get; set; }
        
        public int Quantidade { get; set; }
        
        [Required]
        [DataType(DataType.Currency)]
        public double Valor { get; set; }
        
        [DataType(DataType.Date)]
        public DateTime Data { get; set; }
        
        public string Fornecedor { get; set; }

        public Pedido() { }

        public Pedido(int pedidoId, string produto, int quantidade, double valor, DateTime data, string fornecedor)
        {
            PedidoId = pedidoId;
            Produto = produto;
            Quantidade = quantidade;
            Valor = valor;
            Data = data;
            Fornecedor = fornecedor;
        }

        public void CadastrarPedido(Pedido pedido)
        {
            Console.WriteLine($"Pedido {pedido.PedidoId} cadastrado...");
        }

        public List<Pedido> ListarPedidos()
        {
            List<Pedido> list = new List<Pedido>();
            return list;
        }
    }
}

WebAppPedidos/Controllers/PedidoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebAppPedidos.Data;
using WebAppPedidos.Models;

namespace WebAppPedidos.Controllers
{
    // Gustavo Anderson
    public class PedidoController : Controller
    {
        private readonly PedidoContext _context;

        public PedidoController(PedidoContext context)
        {
            _context = context;
        }
        public IActionResult CadastrarPedido()
        {
            ViewData["existePedido"] = TempData["existePedidoInfo"];
            return View();
        }
        public IActionResult ListarPedidos()
        {
            List<Pedido> lista;
            try
            {
                lista = _context.Pedido.Where(p => p != null).ToList();
            }
            catch (Exception exception)
            {
                throw exception;
            }
            ViewData["ListaPedidos"] = lista;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> SalvarPedido([Bind("PedidoId, Produto, Quantidade, Valor, Data, Fornecedor")] Pedido pedido)
        {
            try
            {
                Pedido p = _context.Pedido.FirstOrDefault(ped => ped.Produto == pedido.Produto);

                if (p != null)
                {
                    TempData["existePedidoInfo"] = "Pedido já foi cadastrado";
                    return RedirectToAction(nameof(CadastrarPedido));
                }
                else
                {
                    pedido.Data = DateTime.Now;
                    _context.Add(pedido);
                    await _context.SaveChangesAsync();
                }
            }
            catch (Exception e) { throw e; }
            return RedirectToAction(nameof(ListarPedidos));
        }
    }
}

WebAppPedidos/Views/Pedido/CadastrarPedido.cshtml
<title>Cadastro de Pedidos</title>
<body>
    <h2>Criar Pedido</h2>
    <br />
    <div class="row">
        <div class="col-md-4">
            @using (Html.BeginForm("SalvarPedido", "Pedido", FormMethod.Post))
            {
                <div class="form-group">
                    <label for="produto">Produto</label><br>
                    <input type="text" id="produto" name="produto" required><br>
                </div>
                <br />
                <div class="form-group">
                    <label for="quantidade">Quantidade</label><br>
                    <input type="text" id="quantidade" name="quantidade"><br>
                </div>
                <br />
                <div class="form-group">
                    <label for="valor">Valor</label><br>
                    <input type="text" id="valor" name="valor" required><br>
                </div>
                <br />
                <div class="form-group">
                    <label for="data">Data</label><br>
                    <input type="text" id="data" name="data"><br>
                </div>
                <br />
                <div class="form-group">
                    <label for="fornecedor">Fornecedor</label><br>
                    <input type="text" id="fornecedor" name="fornecedor"><br>
                </div>
                <br />
                <input type="submit" value="Salvar" />
            }
        </div>
    </div>
</body>
@{ var existePedidoInfo = ViewData["existePedido"];
    if (existePedidoInfo != null)
    {
        <script>alert("Este pedido já foi cadastrado.")</script>
    }
}

WebAppPedidos/Views/Pedido/EditarPedido.cshtml
@model WebAppPedidos.Models.Pedido
@{ var pedido = ViewData["pedido"] as WebAppPedidos.Models.Pedido; }

<head>
    <title>Alterar Pedido</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body class="jumbotron">
    <h2>Alterar Pedido</h2>
    <br />
    <div class="row">
        <div class="col-md-4">
            @using (Html.BeginForm("Editar", "Pedido", FormMethod.Post))
            {
                <div class="form-group">
                    <label for="produto">Produto</label><br>
                    <input type="text" id="produto" name="produto" value="@pedido.Produto" required><br>
                </div>
                <div class="form-group">
                    <label for="quantidade">Quantidade</label><br>
                    <input type="number" step="1" id="quantidade" name="quantidade" value="@pedido.Quantidade"><br>
                </div>
                <div class="form-group">
                    <label for="valor">Valor</label><br>
                    <input type="number" step="1" id="valor" name="valor" required value="@pedido.Valor"><br>
                </div>
                <div class="form-group">
                    <label for="data">Data</label><br>
                    <input type="text" id="data" name="data" value="@pedido.Data"><br>
                </div>
                <div class="form-group">
                    <label for="fornecedor">Fornecedor</label><br>
                    <input type="text" id="fornecedor" name="fornecedor" value="@pedido.Fornecedor"><br>
                </div>
                <button class="btn btn-primary btn-lg" type="submit">Salvar</button>
                <div class="form-group">
                    <input type="hidden" id="pedidoId" name="pedidoId" value="@pedido.PedidoId" />
                </div>
            }
        </div>
    </div>
</body>

WebAppPedidos/Views/Pedido/ListarPedidos.cshtml
@model IEnumerable<WebAppPedidos.Models.Pedido>
@{ var listPedidos = ViewData["ListaPedidos"] as List<WebAppPedidos.Models.Pedido>; }

<head>
    <title>Lista de Pedidos</title>
    <meta charset="utf-8" />
    <style>
        th, td {
            text-align: left;
            padding: 15px;
        }

        td {
            background-color: #D3D3D3;
        }

        table {
            border: 1px solid black;
            border-collapse: collapse;
        }
    </style>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body class="jumbotron">
    <h2>Gerenciamento de Pedidos</h2>
    <br />
    <a href="/Pedido/CadastrarPedido">Cadastrar Pedido</a>
    <br />
    <br />
    <table class="w3-table jumbotron">
        <tr>
            <th class="col-mg-2">@Html.DisplayNameFor(model => model.Produto)</th>
            <th class="col-mg-2">@Html.DisplayNameFor(model => model.Quantidade)</th>
            <th class="col-mg-2">@Html.DisplayNameFor(model => model.Valor)</th>
            <th class="col-mg-2">@Html.DisplayNameFor(model => model.Data)</th>
            <th class="col-mg-2">@Html.DisplayNameFor(model => model.Fornecedor)</th>
            <th></th>
        </tr>
        @{
            if (listPedidos != null)
            {
                foreach (WebAppPedidos.Models.Pedido pedido in listPedidos)
                {
                    <tr>
                        <td>@pedido.Produto</td>
                        <td>@pedido.Quantidade</td>
                        <td>@pedido.Valor</td>
                        <td>@pedido.Data</td>
                        <td>@pedido.Fornecedor</td>
                        <td>
                            <a href="@Url.ActionLink("EditarPedido", "Pedido", new { id = @pedido.PedidoId })">Editar</a> |
                            <a href="@Url.ActionLink("RemoverPedido", "Pedido", new { id = @pedido.PedidoId })">Deletar</a>
                        </td>
                    </tr>
                }
            }
        }
    </table>
    <p style="float: left;"><b>Data de atualização:</b>
    <p style="float: left;" id="data"></p>
</body>

<script>
    var d = new Date();
    var hoje = new Date();
    var yyyy = hoje.getFullYear();

    var dd = hoje.getDate().toString();
    if (dd.length == 1) {
        dd = '0' + dd;
    }

    var mm = (hoje.getMonth() + 1).toString();
    if (mm.length == 1) {
        mm = '0' + mm;
    }

    var horas = hoje.getHours();
    if (horas.toString().length == 1) {
        horas = '0' + horas;
    }

    var minutos = hoje.getMinutes();
    if (minutos.toString().length == 1) {
        minutos = '0' + minutos;
    }

    var segundos = hoje.getSeconds();
    if (segundos.toString().length == 1) {
        segundos = '0' + segundos;
    }

    d = dd + "/" + mm + "/" + yyyy + " " + horas + ":" + minutos + ":" + segundos;
    document.getElementById("data").innerHTML = d;
</script>